version: '3.8'

services:
  app:
    build: .
    container_name: diabetes_reminder_app
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - PORT=8000
